import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
// import 'materialize-css/dist/js/materialize.min.js';
import Provider from "@/redux/provider";
import dynamic from "next/dynamic";
import Head from "next/head";


const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Boomershub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
